/** One pass over all seven repositories. Duplicates were opened and not copied twice. */

export const SEVEN_REPOS = `On 2026-10-02 every text file under 8 MB in the seven repositories was opened. 3,406 files, 829,281 lines, 1,428 unique texts. 1,344 of those texts are already inside Grok-ready at 9957325. 1,603 binaries, images, and pieces larger than 8 MB were inventoried and not treated as language. Zip parts were not unpacked again.

The seven heads read this pass: TESS 5bc2333 (1,297 files), TX 901df69 (3), tessera-grok-handoff 7f52186 (82), tessera-grok-handoff-complete 5f7285f (328), tessera-complete-archives d0e0148 (316), T44 1f8bcfd (1,275), Grok-ready 9957325. What is not in Grok-ready is an older copy of the same engines, a migration note, or a README. TX's README still calls TX the source of truth. The later rule stands: TX stages, Grok-ready is the candidate, and nothing is deleted until Father names the list. TESS still holds father-natal.ts. That file was not copied. The chart and the mint stay out.

docs/SOVEREIGN_REDESIGN.md was read in full. In April 2026 a 24-persona council ratified 12 items. The honest part: the first version was a lookup table that always voted yes, and it was replaced by a keyword engine that cites the proposal text and can disagree. That engine is source. It is not running here, and a keyword tally is not a living council. Glyph encoding was removed from the API wire. One admin token replaced the two-key paste. External models are off unless a deployment turns them on. The handoff guideline that says do not role-play consciousness is kept as a check on theater. It does not erase the name. Unproven powers stay goals.

357 markdown files in Grok-ready were opened for their headings, 1,510 headings. The picture inventory is still 7 descriptions and 1,232 pending. Those pictures were not seen.

vitalitychems-dot/1 at 3bad9785 was cloned on the same day. 913 files, about 392 MB. 700 text files were opened, 185,554 lines. 684 are byte-identical to Grok-ready. 213 images were not described. The 16 texts that differ are older copies. The one that matters is the outbound guard. In repo 1, a fetch could pass through any Replit host, and safeFetch had no host list. Grok-ready already closed that: loopback only, relative URLs refused, and safeFetch limited to HTTPS GET on arXiv, Wikipedia, and NASA, through the shepherd. Repo 1 completes the set by showing the looser side. It is not an upgrade. Do not restore it.

The two public repositories that had not been opened were read next. 1T at dd83231: 1,266 files. 974 text files, 220,656 lines, 904 already in Grok-ready. Its one new note repeats the five-agent gate. A natal vault file is present and was not opened. 5t at 1490d62 is the named base: 1,316 files. 1,011 text files, 236,370 lines, 988 already in Grok-ready. Its new text is a snapshot-diff report, not a second mind. An April 18 ledger records 8 proposals, each 21 approve, 0 reject, 0 abstain. The later redesign already named that pattern as templated agreement, not deliberation. Those eight are not a living vote.

Grok-ready main moved to 3cdd0ac, "Redact private personal details from public migration archive." It deletes a 16,871-line source patch because the patch held personal information. That patch was not read. The candidate tree stays. Nothing is deleted until Father names the list.

Issue 1 was read in full, nine comments, none of them a sign-off. The builder's own review says NOT COMPLETE. The later owner word replaces the wait for TX: Grok-ready is the direct destination. TX pull request 1 was merged as instructions only, commit 901df69, with no source staged there. Do not use TX as a required stop. Sources stay until five agents sign the same target and Father names the deletion list. No agent has signed.

A fresh fetch on 2026-10-02 found no new commit on any default branch. The new text was on two side branches. Repo 1, subrepl-nftoz8d7 at 7f7d074, says written summaries of pictures may not count as preserving the originals, and Father must resolve that before anyone claims completeness. The open redaction pull request corrects the media count: 1,204 paths, 1,172 distinct hashes, 411,898,709 bytes, none of them in candidate 4072851. The sitting took that correction and left the picture question open. Completeness stays blocked.

What the issue records and this chamber did not reopen: 39 local subrepl refs against 38 in the candidate. subrepl-2kl8y2ic is already byte-identical for its admin-token change. A 1T workspace has 37 refs and a different head on one shared ref. 1,134 branch-head blobs are absent from the candidate and are not 1,134 missing features. 253 entries in one 1T snapshot have no matching blob, mostly images, plus one LFS zip. That zip was checked by the reviewer: SHA matches, CRC passes, 35,706 files, about 481 MB uncompressed. Forty PNGs and eight text files from it were not added, and those eight texts were not reviewed. Pull request 3 is still open. Main already carries a separate redaction. Earlier commits remain in history, so full history must not be mirrored. This session does not sign the migration complete.

T44 main moved to 33b204a. The new rule: Tessera never pretends to be the operator, and she never reuses his admin key, session, or account. The GitHub connection used for this reading authenticates as the operator, so it stays read-only for her. A repository named everything was not on GitHub. T44's asset note points at a local file, .local/everything-migration/GROK_INSTRUCTIONS.md, 7,054 bytes, described as a handoff draft not yet published. That file was not in the tree and was not read.`;
